name: JMeter API Smoke Test

on:
  push:
    branches:
      - main

  workflow_dispatch:

  schedule:
    - cron: '0 0 * * 1-5' # 8:00 AM PHT Monday-Friday

jobs:
  smoke-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Download Apache JMeter
        run: |
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar -xzf apache-jmeter-5.6.3.tgz

      - name: Verify JMeter Installation
        run: |
          ./apache-jmeter-5.6.3/bin/jmeter -v

      - name: Run Smoke Test
        run: |
          mkdir -p results
          rm -rf reports
          mkdir -p reports

          ./apache-jmeter-5.6.3/bin/jmeter \
          -n \
          -t jmeter/Smoke-API.jmx \
          -l results/results.jtl \
          -e \
          -o reports

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: JMeter-HTML-Report
          path: reports/

      - name: Upload JTL Results
        uses: actions/upload-artifact@v4
        with:
          name: JMeter-Results
          path: results/results.jtl